### ISSUE TITLE
Blank Page when cloning app

### ISSUE THREAD

**Issue by jerezjustin** [RodSoriano/booking-app#7]
When cloning the app, you get a blank page due to an error importing the resources needed to bootstrap Inertia. This could be solved by changing the following lines in your layout file `resources/views/app.blade.php`:

```php
6    <link href="public/css/app.css" rel="stylesheet" />
7    <script src="public/js/app.js" defer></script>
```

to

```php
6    <link href="/css/app.css" rel="stylesheet" />
7    <script src="/js/app.js" defer></script>
```

This error happens because these files live in the `public` folder which at the end is translated to the root route `/`.

Please try it on your local machine to see if it works.

**Comment by RodSoriano** [comment]
Thank you for your feedback Justin, sorry for the inconvenience, in this case I added the "public" part of the path since in the production server the mapping of the application is somewhat different, and there it needs the public path to be added in order for the application to run, since this repository is the one being taken for the code base of the project that is why, I will try to take into consideration that to leave the repository as it is for anyone who want to use it can do so, just keep in mind this issue if you use the repository for production, ours is running on "Hostinger".

The error that production servers gives if the path is left as: 
```
6  <link href="/css/app.css" rel="stylesheet"/>
7  <script src="/js/app.js" defer></script>
```
is:

`production.server/js/app.js was not found, 404`
`Script could not be loaded <production.server/js/app.js error on load.>`

And the same is for the styles. So in the meantime this is being fixed the workaround is to edit the path for both the css and the js script.

For development I can recommend this:
```
6 <link href="{{ mix('css/app.css') }}" rel="stylesheet">
```
It will give you the ability to run `npm run watch` this  will compile the application every time you save a file on `resources/*`

**Comment by RodSoriano** [comment]
The issue has been fixed for development on the branch "FTR-101". You can refer to this issue section for any type of configuration.
